test_bitstream = executable('test_bitstream',
  'test_bitstream.c',
  dependencies : next264_dep)
test('bitstream', test_bitstream)

test_nal = executable('test_nal',
  'test_nal.c',
  dependencies : next264_dep)
test('nal', test_nal)

test_transform = executable('test_transform',
  'test_transform.c',
  dependencies : next264_dep)
test('transform', test_transform)

test_cavlc = executable('test_cavlc',
  'test_cavlc.c',
  dependencies : next264_dep)
test('cavlc', test_cavlc)

test_mc = executable('test_mc',
  'test_mc.c',
  dependencies : next264_dep)
test('mc', test_mc)

test_cabac = executable('test_cabac',
  'test_cabac.c',
  dependencies : next264_dep)
test('cabac', test_cabac)

test_trellis = executable('test_trellis',
  'test_trellis.c',
  dependencies : next264_dep)
test('trellis', test_trellis)

test_threadpool = executable('test_threadpool',
  'test_threadpool.c',
  dependencies : next264_dep)
test('threadpool', test_threadpool)
